name: todo_server
description: A sample command-line application.
version: 1.0.0
# homepage: https://www.example.com

environment:
  sdk: '>=2.18.2 <3.0.0'

dependencies:
  mongo_dart: ^0.8.0
  http_server: ^1.0.0

dev_dependencies:
  lints: ^2.0.0
  test: ^1.16.0
